# choice of solver
[solver]
type = cycle-avg-joule-coupled


[cycle-avg-joule-coupled]
max-iters = 20
solve-em-every-n = 50
axisymmetric = True
input-power = 18000.0
initial-input-power = 18000.0
plasma-solver = lomach
fixed-conductivity = False

[loMach]
axisymmetric = true
mesh = ../../mesh/torch-flow-refine.msh
ref_levels = 0
order = 3
outputFreq = 1
timingFreq = 1
openSystem = True
flow-solver = tomboulides
thermo-solver = reacting-flow
turb-model = algebraic-rans
algebraic-rans/max-mixing-length = 0.01
algebraic-rans/von-karman = 0.41
algebraic-rans/filter = True
algebraic-rans/filter-order = 1

[loMach/reacting]
eddy-Pr = 100.0
eddy-Sc = 100.0

[loMach/reactingFlow]
sub-steps = 1
implicit-chemistry = true
implicit-chemistry/verbose = true
implicit-chemistry/species_min = 1e-15


[loMach/tomboulides]
numerical-integ = false

[spongeMultiplier]
plane = True
planeNormal = '0 1 0'
planePoint = '0 0.45 0'
planeWidth = 0.01
planeMult = 100.0


[io]
outdirBase = output-torch
enableRestart = True
restartMode = singleFileReadWrite

# Set bdfOrder = 1 for restart testing purposes
[time]
enableConstantTimestep = True
#dt_fixed = 1e-8
dt_fixed = 1e-7
#dt_fixed = 1e-6
integrator = curlcurl
bdfOrder = 1
maxSolverIteration = 200
solverRelTolerance = 1.0e-12

[boundaryConditions]
numWalls = 4
numInlets = 1
numOutlets = 1

# NB: patch = 2 is the axis

[boundaryConditions/wall1]
# Bottom wall
patch = 3
type = viscous_isothermal
temperature = 300.0

[boundaryConditions/wall2]
# Top wall
patch = 7
type = viscous_isothermal
temperature = 300.0

[boundaryConditions/wall3]
# Torch outer wall
patch = 8
type = viscous_isothermal
temperature = 300.0

[boundaryConditions/inlet1]
patch = 4
type = uniform
velocity = '0.0 0.706'
swirl = 40.0
temperature = 300.0

[boundaryConditions/outlet1]
patch = 6
type = uniform
pressure = 0.0

[boundaryConditions/wall4]
patch = 5
type = viscous_isothermal
temperature = 300.0

###########################################
#        PLASMA MODELS
###########################################
[plasma_models]
species_number = 7
ambipolar = True
two_temperature = False
gas_model = perfect_mixture
chemistry_model = 'mass_action_law'
transport_model = argon_mixture
argon_ternary/third_order_thermal_conductivity = True

[plasma_models]
radiation_model = net_emission

[plasma_models/radiation_model/net_emission]
coefficient = tabulated
tabulated/filename = ../../radiation-data/nec_sample.0.h5
tabulated/x_log = False
tabulated/f_log = False
tabulated/order = 1

[atoms]
numAtoms = 2

[atoms/atom1]
name = 'Ar'
mass = 39.948e-3 # [kg/mol]

[atoms/atom2]
name = 'E'
mass = 5.48579908782496e-7 # [kg/mol]

[species]
numSpecies = 7
background_index = 7

[species/species7]
name = 'Ar'
composition = '{Ar : 1}'
formation_energy = 0.0
level_degeneracy = 1
initialMassFraction = 1.0
perfect_mixture/constant_molar_cv = 1.5
perfect_mixture/constant_molar_cp = 2.5

[species/species6]
name = 'E'
composition = '{E : 1}'
formation_energy = 0.0
level_degeneracy = 1
initialMassFraction = 0.0
initialElectronTemperature = 300.0
# if gas_model is perfect_mixture, requires heat capacities from input.
# molar heat capacities in unit of universal gas constant.
perfect_mixture/constant_molar_cv = 1.5
perfect_mixture/constant_molar_cp = 2.5

[species/species5]
name = 'Ar.+1'
composition = '{Ar : 1, E : -1}'
formation_energy = 1520571.3883  # [J/mol]  = 15.7596119 eV # Ionization energy (Not sure what the units should be here)
level_degeneracy = 4
initialMassFraction = 0.0
perfect_mixture/constant_molar_cv = 1.5
perfect_mixture/constant_molar_cp = 2.5

[species/species1]
name = 'Ar_m'
composition = '{Ar : 1}'
formation_energy = 1116860.96186 # [J/mol]  =  11.5754 eV (weighted value such that n_m = the number densities of the two metastables) # (E_f = E_ev * spc.e * spc.N_A where E_f in [J/mol] and E_ev in [eV])   Exitation energy of metastables
level_degeneracy = 6
initialMassFraction = 0.0
perfect_mixture/constant_molar_cv = 1.5
perfect_mixture/constant_molar_cp = 2.5

[species/species2]
name = 'Ar_r'
composition = '{Ar : 1}'
formation_energy = 1130867.391486 # [J/mol]  =  11.7206 eV # Exitation energy of resonance levels
level_degeneracy = 6
initialMassFraction = 0.0
perfect_mixture/constant_molar_cv = 1.5
perfect_mixture/constant_molar_cp = 2.5

[species/species3]
name = 'Ar_p'
composition = '{Ar : 1}'
formation_energy = 1269949.8858896866 # [J/mol]  =  13.16210306730009 eV # Exitation energy of 4p levels
level_degeneracy = 36
initialMassFraction = 0.0
perfect_mixture/constant_molar_cv = 1.5
perfect_mixture/constant_molar_cp = 2.5

[species/species4]
name = 'Ar_h'
composition = '{Ar : 1}'
formation_energy = 1393459.40561185 # [J/mol]  =  13.16210306730009 eV # Exitation energy of 4p levels
level_degeneracy = 333
initialMassFraction = 0.0
perfect_mixture/constant_molar_cv = 1.5
perfect_mixture/constant_molar_cp = 2.5


# Species ordering
# [Ar_s, Ar+, E, Ar]
# Ar_s is lumped excited state

[reactions]
number_of_reactions = 30

# ground ionization
[reactions/reaction1]
equation = 'Ar + E => Ar.+1 + 2 E'
reaction_energy = 1520571.3883 # [J/mol]
reactant_stoichiometry = '0 0 0 0 0 1 1'
product_stoichiometry = '0 0 0 0 1 2 0'
model = tabulated
tabulated/filename = 'rate-coefficients/Ionization_Ground.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

# ground recombination
[reactions/reaction2]
equation = 'Ar.+1 + 2 E => Ar + E'
reaction_energy = -1520571.3883 # [J/mol]
reactant_stoichiometry = '0 0 0 0 1 2 0'
product_stoichiometry = '0 0 0 0 0 1 1'
model = tabulated
tabulated/filename = 'rate-coefficients/Recombination_Ground.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

# meta ionization
[reactions/reaction3]
equation = 'Ar_m + E => Ar.+1 + 2 E'
reaction_energy = 403710.42644000007 #1520571.3883 - 1116860.96186 # [J/mol]
reactant_stoichiometry = '1 0 0 0 0 1 0'
product_stoichiometry = '0 0 0 0 1 2 0'
model = tabulated
tabulated/filename = 'rate-coefficients/Ionization_meta.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

# meta recombination
[reactions/reaction4]
equation = 'Ar.+1 + 2 E => Ar_m + E'
reaction_energy = -403710.42644000007 #-(1520571.3883-1116860.96186) # [J/mol]
reactant_stoichiometry = '0 0 0 0 1 2 0'
product_stoichiometry = '1 0 0 0 0 1 0'
model = tabulated
tabulated/filename = 'rate-coefficients/Recombination_meta.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

# meta excitation
[reactions/reaction5]
equation = 'Ar + E => Ar_m + E'
reaction_energy = 1116860.96186 # [J/mol]
reactant_stoichiometry = '0 0 0 0 0 1 1'
product_stoichiometry = '1 0 0 0 0 1 0'
model = tabulated
tabulated/filename = 'rate-coefficients/Excitation_meta.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

# meta deexcitation
[reactions/reaction6]
equation = 'Ar_m + E => Ar + E'
reaction_energy = -1116860.96186 # [J/mol]
reactant_stoichiometry = '1 0 0 0 0 1 0'
product_stoichiometry = '0 0 0 0 0 1 1'
model = tabulated
tabulated/filename = 'rate-coefficients/Deexcitation_meta.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

# res ionization
[reactions/reaction7]
equation = 'Ar_r + E => Ar.+1 + 2 E'
reaction_energy = 389703.99681399995 #1520571.3883-1130867.391486 # [J/mol]
reactant_stoichiometry = '0 1 0 0 0 1 0'
product_stoichiometry = '0 0 0 0 1 2 0'
model = tabulated
tabulated/filename = 'rate-coefficients/Ionization_res.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

# res recombination
[reactions/reaction8]
equation = 'Ar.+1 + 2 E => Ar_r + E'
reaction_energy = -389703.99681399995 #-(1520571.3883-1130867.391486) # [J/mol]
reactant_stoichiometry = '0 0 0 0 1 2 0'
product_stoichiometry = '0 1 0 0 0 1 0'
model = tabulated
tabulated/filename = 'rate-coefficients/Recombination_res.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

# res excitation
[reactions/reaction9]
equation = 'Ar + E => Ar_r + E'
reaction_energy = 1130867.391486 # [J/mol]
reactant_stoichiometry = '0 0 0 0 0 1 1'
product_stoichiometry = '0 1 0 0 0 1 0'
model = tabulated
tabulated/filename = 'rate-coefficients/Excitation_res.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

# res deexcitation
[reactions/reaction10]
equation = 'Ar_r + E => Ar + E'
reaction_energy = -1130867.391486 # [J/mol]
reactant_stoichiometry = '0 1 0 0 0 1 0'
product_stoichiometry = '0 0 0 0 0 1 1'
model = tabulated
tabulated/filename = 'rate-coefficients/Deexcitation_res.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

# fourp ionization
[reactions/reaction11]
equation = 'Ar_p + E => Ar.+1 + 2 E'
reaction_energy = 250621.50241031335# 1520571.3883-1269949.8858896866 # [J/mol]
reactant_stoichiometry = '0 0 1 0 0 1 0'
product_stoichiometry = '0 0 0 0 1 2 0'
model = tabulated
tabulated/filename = 'rate-coefficients/Ionization_fourp.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

# fourp recombination
[reactions/reaction12]
equation = 'Ar.+1 + 2 E => Ar_p + E'
reaction_energy = -250621.50241031335 #-(1520571.3883-1269949.8858896866) # [J/mol]
reactant_stoichiometry = '0 0 0 0 1 2 0'
product_stoichiometry = '0 0 1 0 0 1 0'
model = tabulated
tabulated/filename = 'rate-coefficients/Recombination_fourp.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

# fourp excitation
[reactions/reaction13]
equation = 'Ar + E => Ar_p + E'
reaction_energy = 1269949.8858896866 # [J/mol]
reactant_stoichiometry = '0 0 0 0 0 1 1'
product_stoichiometry = '0 0 1 0 0 1 0'
model = tabulated
tabulated/filename = 'rate-coefficients/Excitation_fourp.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

# fourp deexcitation
[reactions/reaction14]
equation = 'Ar_p + E => Ar + E'
reaction_energy = -1269949.8858896866 # [J/mol]
reactant_stoichiometry = '0 0 1 0 0 1 0'
product_stoichiometry = '0 0 0 0 0 1 1'
model = tabulated
tabulated/filename = 'rate-coefficients/Deexcitation_fourp.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

# higher ionization
[reactions/reaction15]
equation = 'Ar_h + E => Ar.+1 + 2 E'
reaction_energy = 127111.9826881499 # 1520571.3883-1393459.40561185 # [J/mol]
reactant_stoichiometry = '0 0 0 1 0 1 0'
product_stoichiometry = '0 0 0 0 1 2 0'
model = tabulated
tabulated/filename = 'rate-coefficients/Ionization_higher.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

# higher recombination
[reactions/reaction16]
equation = 'Ar.+1 + 2 E => Ar_h + E'
reaction_energy = -127111.9826881499 #-(1520571.3883-1393459.40561185) # [J/mol]
reactant_stoichiometry = '0 0 0 0 1 2 0'
product_stoichiometry = '0 0 0 1 0 1 0'
model = tabulated
tabulated/filename = 'rate-coefficients/Recombination_higher.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

# higher excitation
[reactions/reaction17]
equation = 'Ar + E => Ar_h + E'
reaction_energy = 1393459.40561185 # [J/mol]
reactant_stoichiometry = '0 0 0 0 0 1 1'
product_stoichiometry = '0 0 0 1 0 1 0'
model = tabulated
tabulated/filename = 'rate-coefficients/Excitation_higher.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

# higher deexcitation
[reactions/reaction18]
equation = 'Ar_h + E => Ar + E'
reaction_energy = -1393459.40561185 # [J/mol]
reactant_stoichiometry = '0 0 0 1 0 1 0'
product_stoichiometry = '1 1 0 0 0 1 1'
model = tabulated
tabulated/filename = 'rate-coefficients/Deexcitation_higher.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

#####################

# meta to res
[reactions/reaction19]
equation = 'Ar_m + E => Ar_r + E'
reaction_energy = 14006.429626000114 #1130867.391486-1116860.96186 # [J/mol]
reactant_stoichiometry = '1 0 0 0 0 1 0'
product_stoichiometry = '0 1 0 0 0 1 0'
model = tabulated
tabulated/filename = 'rate-coefficients/StepExcitation_meta_res.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

# res to meta
[reactions/reaction20]
equation = 'Ar_r + E => Ar_m + E'
reaction_energy = -14006.429626000114 #(1130867.391486-1116860.96186) # [J/mol]
reactant_stoichiometry = '0 1 0 0 0 1 0'
product_stoichiometry = '1 0 0 0 0 1 0'
model = tabulated
tabulated/filename = 'rate-coefficients/StepExcitation_res_meta.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

# meta to fourp
[reactions/reaction21]
equation = 'Ar_m + E => Ar_p + E'
reaction_energy = 153088.92402968672 #1269949.8858896866-1116860.96186 # [J/mol]
reactant_stoichiometry = '1 0 0 0 0 1 0'
product_stoichiometry = '0 0 1 0 0 1 0'
model = tabulated
tabulated/filename = 'rate-coefficients/StepExcitation_meta_fourp.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

# fourp to meta
[reactions/reaction22]
equation = 'Ar_p + E => Ar_m + E'
reaction_energy = -153088.92402968672 #(1269949.8858896866-1116860.96186) # [J/mol]
reactant_stoichiometry = '0 0 1 0 0 1 0'
product_stoichiometry = '1 0 0 0 0 1 0'
model = tabulated
tabulated/filename = 'rate-coefficients/StepExcitation_fourp_meta.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

# meta to higher
[reactions/reaction23]
equation = 'Ar_m + E => Ar_h + E'
reaction_energy = 276598.44375185017 #1393459.40561185-1116860.96186 # [J/mol]
reactant_stoichiometry = '1 0 0 0 0 1 0'
product_stoichiometry = '0 0 0 1 0 1 0'
model = tabulated
tabulated/filename = 'rate-coefficients/StepExcitation_meta_higher.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

# higher to meta
[reactions/reaction24]
equation = 'Ar_h + E => Ar_m + E'
reaction_energy = -276598.44375185017 #-(1393459.40561185-1116860.96186) # [J/mol]
reactant_stoichiometry = '0 0 0 1 0 1 0'
product_stoichiometry = '1 0 0 0 0 1 0'
model = tabulated
tabulated/filename = 'rate-coefficients/StepExcitation_higher_meta.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

# res to fourp
[reactions/reaction25]
equation = 'Ar_r + E => Ar_p + E'
reaction_energy = 139082.4944036866# 1269949.8858896866-1130867.391486 # [J/mol]
reactant_stoichiometry = '0 1 0 0 0 1 0'
product_stoichiometry = '0 0 1 0 0 1 0'
model = tabulated
tabulated/filename = 'rate-coefficients/StepExcitation_res_fourp.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

# fourp to res
[reactions/reaction26]
equation = 'Ar_p + E => Ar_r + E'
reaction_energy = -139082.4944036866 #(1269949.8858896866-1130867.391486) # [J/mol]
reactant_stoichiometry = '0 0 1 0 0 1 0'
product_stoichiometry = '0 1 0 0 0 1 0'
model = tabulated
tabulated/filename = 'rate-coefficients/StepExcitation_fourp_res.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

# res to higher
[reactions/reaction27]
equation = 'Ar_r + E => Ar_h + E'
reaction_energy = 262592.01412585005 #1393459.40561185-1130867.391486 # [J/mol]
reactant_stoichiometry = '0 1 0 0 0 1 0'
product_stoichiometry = '0 0 0 1 0 1 0'
model = tabulated
tabulated/filename = 'rate-coefficients/StepExcitation_res_higher.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

# higher to res
[reactions/reaction28]
equation = 'Ar_h + E => Ar_r + E'
reaction_energy = -262592.01412585005 #(1393459.40561185-1130867.391486) # [J/mol]
reactant_stoichiometry = '0 0 0 1 0 1 0'
product_stoichiometry = '0 1 0 0 0 1 0'
model = tabulated
tabulated/filename = 'rate-coefficients/StepExcitation_higher_res.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

# fourp to higher
[reactions/reaction29]
equation = 'Ar_p + E => Ar_h + E'
reaction_energy = 123509.51972216344 #1393459.40561185-1269949.8858896866 # [J/mol]
reactant_stoichiometry = '0 0 1 0 0 1 0'
product_stoichiometry = '0 0 0 1 0 1 0'
model = tabulated
tabulated/filename = 'rate-coefficients/StepExcitation_fourp_higher.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

# higher to fourp
[reactions/reaction30]
equation = 'Ar_h + E => Ar_p + E'
reaction_energy = -123509.51972216344 #-(1393459.40561185-1269949.8858896866) # [J/mol]
reactant_stoichiometry = '0 0 0 1 0 1 0'
product_stoichiometry = '0 0 1 0 0 1 0'
model = tabulated
tabulated/filename = 'rate-coefficients/StepExcitation_higher_fourp.h5'
tabulated/x_log = False
tabulated/f_log = True
tabulated/order = 1
detailed_balance = False

#---------------------------------------
# Controls for EM-only solver
# mesh = ../mesh/torch-em-coarse2.msh
# order       =  3                 # FE order (polynomial degree)
#---------------------------------------
[em]
mesh = ../../mesh/torch-em-NEWCOIL.msh
order       =  2                 # FE order (polynomial degree)
ref_levels  =  0
max_iter    =  1000              # max number of iterations
rtol        =  1.0e-12           # solver relative tolerance
atol        =  1.0e-18           # solver absolute tolerance
top_only    =  false             # run current through top branch only
bot_only    =  false             # run current through bottom branch only
current_amplitude = 4e6        # run 1 of heating # A/m^2 (with reactions
current_frequency = 6e6          # 1/s
permeability = 1.25663706e-6     # m * kg / s^2 / A^2
